---
  intra:
    client: "Put your UID" #UID
    secret: "Put your secret key" #SECRET
    uri: "https://api.intra.42.fr/v2/oauth/token"
    endpoint: "https://api.intra.42.fr/v2/"
    scopes: "public"
